mv -if Higgs650/*/*/*/*/ReducedSelection_* Higgs650/
mv -if Higgs750/*/*/*/*/ReducedSelection_* Higgs750/
mv -if Higgs1000/*/*/*/*/ReducedSelection_* Higgs1000/
mv -if VBFHiggs650/*/*/*/*/ReducedSelection_* VBFHiggs650/
mv -if VBFHiggs750/*/*/*/*/ReducedSelection_* VBFHiggs750/
mv -if VBFHiggs1000/*/*/*/*/ReducedSelection_* VBFHiggs1000/
mv -if RSGraviton600/*/*/*/*/ReducedSelection_* RSGraviton600/
mv -if RSGraviton800/*/*/*/*/ReducedSelection_* RSGraviton800/
mv -if RSGraviton1000/*/*/*/*/ReducedSelection_* RSGraviton1000/
mv -if RSGraviton1200/*/*/*/*/ReducedSelection_* RSGraviton1200/
mv -if RSGraviton1400/*/*/*/*/ReducedSelection_* RSGraviton1400/
mv -if RSGraviton1600/*/*/*/*/ReducedSelection_* RSGraviton1600/
mv -if RSGraviton1800/*/*/*/*/ReducedSelection_* RSGraviton1800/
mv -if RSGraviton2000/*/*/*/*/ReducedSelection_* RSGraviton2000/
mv -if RSGraviton2500/*/*/*/*/ReducedSelection_* RSGraviton2500/
mv -if RSGraviton3000/*/*/*/*/ReducedSelection_* RSGraviton3000/
mv -if RSGraviton3500/*/*/*/*/ReducedSelection_* RSGraviton3500/
mv -if RSGraviton4000/*/*/*/*/ReducedSelection_* RSGraviton4000/
mv -if RSGraviton4500/*/*/*/*/ReducedSelection_* RSGraviton4500/
mv -if BulkGraviton600/*/*/*/*/ReducedSelection_* BulkGraviton600/
mv -if BulkGraviton800/*/*/*/*/ReducedSelection_* BulkGraviton800/
mv -if BulkGraviton1000/*/*/*/*/ReducedSelection_* BulkGraviton1000/
mv -if BulkGraviton1200/*/*/*/*/ReducedSelection_* BulkGraviton1200/
mv -if BulkGraviton1400/*/*/*/*/ReducedSelection_* BulkGraviton1400/
mv -if BulkGraviton1600/*/*/*/*/ReducedSelection_* BulkGraviton1600/
mv -if BulkGraviton1800/*/*/*/*/ReducedSelection_* BulkGraviton1800/
mv -if BulkGraviton2000/*/*/*/*/ReducedSelection_* BulkGraviton2000/
mv -if BulkGraviton2500/*/*/*/*/ReducedSelection_* BulkGraviton2500/
mv -if BulkGraviton3000/*/*/*/*/ReducedSelection_* BulkGraviton3000/
mv -if BulkGraviton3500/*/*/*/*/ReducedSelection_* BulkGraviton3500/
mv -if BulkGraviton4000/*/*/*/*/ReducedSelection_* BulkGraviton4000/
mv -if BulkGraviton4500/*/*/*/*/ReducedSelection_* BulkGraviton4500/
mv -if VBFBulkGraviton600/*/*/*/*/ReducedSelection_* VBFBulkGraviton600/
mv -if VBFBulkGraviton800/*/*/*/*/ReducedSelection_* VBFBulkGraviton800/
mv -if VBFBulkGraviton1000/*/*/*/*/ReducedSelection_* VBFBulkGraviton1000/
mv -if VBFBulkGraviton1200/*/*/*/*/ReducedSelection_* VBFBulkGraviton1200/
mv -if VBFBulkGraviton1400/*/*/*/*/ReducedSelection_* VBFBulkGraviton1400/
mv -if VBFBulkGraviton1600/*/*/*/*/ReducedSelection_* VBFBulkGraviton1600/
mv -if VBFBulkGraviton1800/*/*/*/*/ReducedSelection_* VBFBulkGraviton1800/
mv -if VBFBulkGraviton2000/*/*/*/*/ReducedSelection_* VBFBulkGraviton2000/
mv -if VBFBulkGraviton2500/*/*/*/*/ReducedSelection_* VBFBulkGraviton2500/
mv -if VBFBulkGraviton3000/*/*/*/*/ReducedSelection_* VBFBulkGraviton3000/
mv -if VBFBulkGraviton3500/*/*/*/*/ReducedSelection_* VBFBulkGraviton3500/
mv -if VBFBulkGraviton4000/*/*/*/*/ReducedSelection_* VBFBulkGraviton4000/
mv -if VBFBulkGraviton4500/*/*/*/*/ReducedSelection_* VBFBulkGraviton4500/
mv -if WprimeToWZ600/*/*/*/*/ReducedSelection_* WprimeToWZ600/
mv -if WprimeToWZ800/*/*/*/*/ReducedSelection_* WprimeToWZ800/
mv -if WprimeToWZ1000/*/*/*/*/ReducedSelection_* WprimeToWZ1000/
mv -if WprimeToWZ1200/*/*/*/*/ReducedSelection_* WprimeToWZ1200/
mv -if WprimeToWZ1400/*/*/*/*/ReducedSelection_* WprimeToWZ1400/
mv -if WprimeToWZ1600/*/*/*/*/ReducedSelection_* WprimeToWZ1600/
mv -if WprimeToWZ1800/*/*/*/*/ReducedSelection_* WprimeToWZ1800/
mv -if WprimeToWZ2000/*/*/*/*/ReducedSelection_* WprimeToWZ2000/
mv -if WprimeToWZ2500/*/*/*/*/ReducedSelection_* WprimeToWZ2500/
mv -if WprimeToWZ3000/*/*/*/*/ReducedSelection_* WprimeToWZ3000/
mv -if WprimeToWZ3500/*/*/*/*/ReducedSelection_* WprimeToWZ3500/
mv -if WprimeToWZ4000/*/*/*/*/ReducedSelection_* WprimeToWZ4000/
mv -if WprimeToWZ4500/*/*/*/*/ReducedSelection_* WprimeToWZ4500/
mv -if WJets/*/*/*/*/ReducedSelection_* WJets/
mv -if WJets_madgraph/*/*/*/*/ReducedSelection_* WJets_madgraph/
mv -if WJets100/*/*/*/*/ReducedSelection_* WJets100/
mv -if WJets200/*/*/*/*/ReducedSelection_* WJets200/
mv -if WJets400/*/*/*/*/ReducedSelection_* WJets400/
mv -if WJets600/*/*/*/*/ReducedSelection_* WJets600/
mv -if WJets600bis/*/*/*/*/ReducedSelection_* WJets600bis/
mv -if WJets800/*/*/*/*/ReducedSelection_* WJets800/
mv -if WJets1200/*/*/*/*/ReducedSelection_* WJets1200/
mv -if WJets2500/*/*/*/*/ReducedSelection_* WJets2500/
mv -if TTbar_amcatnlo/*/*/*/*/ReducedSelection_* TTbar_amcatnlo/
mv -if TTbar_powheg/*/*/*/*/ReducedSelection_* TTbar_powheg/
mv -if TTbar_madgraph/*/*/*/*/ReducedSelection_* TTbar_madgraph/
mv -if TTbar600/*/*/*/*/ReducedSelection_* TTbar600/
mv -if TTbar800/*/*/*/*/ReducedSelection_* TTbar800/
mv -if TTbar1200/*/*/*/*/ReducedSelection_* TTbar1200/
mv -if TTbar2500/*/*/*/*/ReducedSelection_* TTbar2500/
mv -if WW/*/*/*/*/ReducedSelection_* WW/
mv -if WZ/*/*/*/*/ReducedSelection_* WZ/
mv -if ZZ/*/*/*/*/ReducedSelection_* ZZ/
mv -if WW_excl/*/*/*/*/ReducedSelection_* WW_excl/
mv -if WZ_excl/*/*/*/*/ReducedSelection_* WZ_excl/
mv -if ZZ_excl/*/*/*/*/ReducedSelection_* ZZ_excl/
mv -if sch/*/*/*/*/ReducedSelection_* sch/
mv -if tch/*/*/*/*/ReducedSelection_* tch/
mv -if tch_bar/*/*/*/*/ReducedSelection_* tch_bar/
mv -if tWch/*/*/*/*/ReducedSelection_* tWch/
mv -if tWch_bar/*/*/*/*/ReducedSelection_* tWch_bar/
mv -if data_mu_2016_runB_v2/*/*/*/*/ReducedSelection_* data_mu_2016_runB_v2/
mv -if data_el_2016_runB_v2/*/*/*/*/ReducedSelection_* data_el_2016_runB_v2/
mv -if data_mu_2016_runC_v2/*/*/*/*/ReducedSelection_* data_mu_2016_runC_v2/
mv -if data_el_2016_runC_v2/*/*/*/*/ReducedSelection_* data_el_2016_runC_v2/
