mkdir data_mu_16dec_25ns_runD_17
mkdir data_mu_16dec_25ns_runD_16
mkdir data_mu_16dec_25ns_runD_15
mkdir data_mu_16dec_25ns_runD_14
mkdir data_mu_16dec_25ns_runD_13
mkdir data_mu_16dec_25ns_runD_12
mkdir data_mu_16dec_25ns_runD_11
mkdir data_mu_16dec_25ns_runD_10
mkdir data_mu_16dec_25ns_runD_9
mkdir data_mu_16dec_25ns_runD_8
mkdir data_mu_16dec_25ns_runD_7
mkdir data_mu_16dec_25ns_runD_6
mkdir data_mu_16dec_25ns_runD_5
mkdir data_mu_16dec_25ns_runD_4
mkdir data_mu_16dec_25ns_runD_3
mkdir data_mu_16dec_25ns_runD_2
mkdir data_mu_16dec_25ns_runD_1
mv data_mu_16dec_25ns_runD/ReducedSelection_17* data_mu_16dec_25ns_runD_17/
mv data_mu_16dec_25ns_runD/ReducedSelection_16* data_mu_16dec_25ns_runD_16/
mv data_mu_16dec_25ns_runD/ReducedSelection_15* data_mu_16dec_25ns_runD_15/
mv data_mu_16dec_25ns_runD/ReducedSelection_14* data_mu_16dec_25ns_runD_14/
mv data_mu_16dec_25ns_runD/ReducedSelection_13* data_mu_16dec_25ns_runD_13/
mv data_mu_16dec_25ns_runD/ReducedSelection_12* data_mu_16dec_25ns_runD_12/
mv data_mu_16dec_25ns_runD/ReducedSelection_11* data_mu_16dec_25ns_runD_11/
mv data_mu_16dec_25ns_runD/ReducedSelection_10* data_mu_16dec_25ns_runD_10/
mv data_mu_16dec_25ns_runD/ReducedSelection_9* data_mu_16dec_25ns_runD_9/
mv data_mu_16dec_25ns_runD/ReducedSelection_8* data_mu_16dec_25ns_runD_8/
mv data_mu_16dec_25ns_runD/ReducedSelection_7* data_mu_16dec_25ns_runD_7/
mv data_mu_16dec_25ns_runD/ReducedSelection_6* data_mu_16dec_25ns_runD_6/
mv data_mu_16dec_25ns_runD/ReducedSelection_5* data_mu_16dec_25ns_runD_5/
mv data_mu_16dec_25ns_runD/ReducedSelection_4* data_mu_16dec_25ns_runD_4/
mv data_mu_16dec_25ns_runD/ReducedSelection_3* data_mu_16dec_25ns_runD_3/
mv data_mu_16dec_25ns_runD/ReducedSelection_2* data_mu_16dec_25ns_runD_2/
mv data_mu_16dec_25ns_runD/ReducedSelection_* data_mu_16dec_25ns_runD_1/

mkdir data_el_16dec_25ns_runD_17
mkdir data_el_16dec_25ns_runD_16
mkdir data_el_16dec_25ns_runD_15
mkdir data_el_16dec_25ns_runD_14
mkdir data_el_16dec_25ns_runD_13
mkdir data_el_16dec_25ns_runD_12
mkdir data_el_16dec_25ns_runD_11
mkdir data_el_16dec_25ns_runD_10
mkdir data_el_16dec_25ns_runD_9
mkdir data_el_16dec_25ns_runD_8
mkdir data_el_16dec_25ns_runD_7
mkdir data_el_16dec_25ns_runD_6
mkdir data_el_16dec_25ns_runD_5
mkdir data_el_16dec_25ns_runD_4
mkdir data_el_16dec_25ns_runD_3
mkdir data_el_16dec_25ns_runD_2
mkdir data_el_16dec_25ns_runD_1
mv data_el_16dec_25ns_runD/ReducedSelection_17* data_el_16dec_25ns_runD_17/
mv data_el_16dec_25ns_runD/ReducedSelection_16* data_el_16dec_25ns_runD_16/
mv data_el_16dec_25ns_runD/ReducedSelection_15* data_el_16dec_25ns_runD_15/
mv data_el_16dec_25ns_runD/ReducedSelection_14* data_el_16dec_25ns_runD_14/
mv data_el_16dec_25ns_runD/ReducedSelection_13* data_el_16dec_25ns_runD_13/
mv data_el_16dec_25ns_runD/ReducedSelection_12* data_el_16dec_25ns_runD_12/
mv data_el_16dec_25ns_runD/ReducedSelection_11* data_el_16dec_25ns_runD_11/
mv data_el_16dec_25ns_runD/ReducedSelection_10* data_el_16dec_25ns_runD_10/
mv data_el_16dec_25ns_runD/ReducedSelection_9* data_el_16dec_25ns_runD_9/
mv data_el_16dec_25ns_runD/ReducedSelection_8* data_el_16dec_25ns_runD_8/
mv data_el_16dec_25ns_runD/ReducedSelection_7* data_el_16dec_25ns_runD_7/
mv data_el_16dec_25ns_runD/ReducedSelection_6* data_el_16dec_25ns_runD_6/
mv data_el_16dec_25ns_runD/ReducedSelection_5* data_el_16dec_25ns_runD_5/
mv data_el_16dec_25ns_runD/ReducedSelection_4* data_el_16dec_25ns_runD_4/
mv data_el_16dec_25ns_runD/ReducedSelection_3* data_el_16dec_25ns_runD_3/
mv data_el_16dec_25ns_runD/ReducedSelection_2* data_el_16dec_25ns_runD_2/
mv data_el_16dec_25ns_runD/ReducedSelection_* data_el_16dec_25ns_runD_1/

mkdir TTbar_powheg_1
mkdir TTbar_powheg_2
mkdir TTbar_powheg_3
mkdir TTbar_powheg_4
mkdir TTbar_powheg_5
mkdir TTbar_powheg_6
mkdir TTbar_powheg_7
mkdir TTbar_powheg_8
mkdir TTbar_powheg_9
mkdir TTbar_powheg_10
mkdir TTbar_powheg_11
mkdir TTbar_powheg_12
mkdir TTbar_powheg_13
mkdir TTbar_powheg_14
mkdir TTbar_powheg_15
mkdir TTbar_powheg_16
mkdir TTbar_powheg_17
mkdir TTbar_powheg_18
mkdir TTbar_powheg_19
mkdir TTbar_powheg_20
mkdir TTbar_powheg_21
mkdir TTbar_powheg_22
mkdir TTbar_powheg_23
mv TTbar_powheg/ReducedSelection_46* TTbar_powheg_23/
mv TTbar_powheg/ReducedSelection_45* TTbar_powheg_23/
mv TTbar_powheg/ReducedSelection_44* TTbar_powheg_22/
mv TTbar_powheg/ReducedSelection_43* TTbar_powheg_22/
mv TTbar_powheg/ReducedSelection_42* TTbar_powheg_21/
mv TTbar_powheg/ReducedSelection_41* TTbar_powheg_21/
mv TTbar_powheg/ReducedSelection_40* TTbar_powheg_20/
mv TTbar_powheg/ReducedSelection_39* TTbar_powheg_20/
mv TTbar_powheg/ReducedSelection_38* TTbar_powheg_19/
mv TTbar_powheg/ReducedSelection_37* TTbar_powheg_19/
mv TTbar_powheg/ReducedSelection_36* TTbar_powheg_18/
mv TTbar_powheg/ReducedSelection_35* TTbar_powheg_18/
mv TTbar_powheg/ReducedSelection_34* TTbar_powheg_17/
mv TTbar_powheg/ReducedSelection_33* TTbar_powheg_17/
mv TTbar_powheg/ReducedSelection_32* TTbar_powheg_16/
mv TTbar_powheg/ReducedSelection_31* TTbar_powheg_16/
mv TTbar_powheg/ReducedSelection_30* TTbar_powheg_15/
mv TTbar_powheg/ReducedSelection_29* TTbar_powheg_15/
mv TTbar_powheg/ReducedSelection_28* TTbar_powheg_14/
mv TTbar_powheg/ReducedSelection_27* TTbar_powheg_14/
mv TTbar_powheg/ReducedSelection_26* TTbar_powheg_13/
mv TTbar_powheg/ReducedSelection_25* TTbar_powheg_13/
mv TTbar_powheg/ReducedSelection_24* TTbar_powheg_12/
mv TTbar_powheg/ReducedSelection_23* TTbar_powheg_12/
mv TTbar_powheg/ReducedSelection_22* TTbar_powheg_11/
mv TTbar_powheg/ReducedSelection_21* TTbar_powheg_11/
mv TTbar_powheg/ReducedSelection_20* TTbar_powheg_10/
mv TTbar_powheg/ReducedSelection_19* TTbar_powheg_10/
mv TTbar_powheg/ReducedSelection_18* TTbar_powheg_9/
mv TTbar_powheg/ReducedSelection_17* TTbar_powheg_9/
mv TTbar_powheg/ReducedSelection_16* TTbar_powheg_8/
mv TTbar_powheg/ReducedSelection_15* TTbar_powheg_8/
mv TTbar_powheg/ReducedSelection_14* TTbar_powheg_7/
mv TTbar_powheg/ReducedSelection_13* TTbar_powheg_7/
mv TTbar_powheg/ReducedSelection_12* TTbar_powheg_6/
mv TTbar_powheg/ReducedSelection_11* TTbar_powheg_6/
mv TTbar_powheg/ReducedSelection_10* TTbar_powheg_5/
mv TTbar_powheg/ReducedSelection_9* TTbar_powheg_5/
mv TTbar_powheg/ReducedSelection_8* TTbar_powheg_4/
mv TTbar_powheg/ReducedSelection_7* TTbar_powheg_4/
mv TTbar_powheg/ReducedSelection_6* TTbar_powheg_3/
mv TTbar_powheg/ReducedSelection_5* TTbar_powheg_3/
mv TTbar_powheg/ReducedSelection_4* TTbar_powheg_2/
mv TTbar_powheg/ReducedSelection_3* TTbar_powheg_2/
mv TTbar_powheg/ReducedSelection_* TTbar_powheg_1/
mkdir TTbar_madgraph_1
mkdir TTbar_madgraph_2
mkdir TTbar_madgraph_3
mv TTbar_madgraph/ReducedSelection_1* TTbar_madgraph_1/
mv TTbar_madgraph/ReducedSelection_2* TTbar_madgraph_2/
mv TTbar_madgraph/ReducedSelection_* TTbar_madgraph_3/
mkdir TTbar_amcatnlo_1
mkdir TTbar_amcatnlo_2
mkdir TTbar_amcatnlo_3
mkdir TTbar_amcatnlo_4
mkdir TTbar_amcatnlo_5
mv TTbar_amcatnlo/ReducedSelection_1* TTbar_amcatnlo_1/
mv TTbar_amcatnlo/ReducedSelection_2* TTbar_amcatnlo_1/
mv TTbar_amcatnlo/ReducedSelection_3* TTbar_amcatnlo_2/
mv TTbar_amcatnlo/ReducedSelection_4* TTbar_amcatnlo_2/
mv TTbar_amcatnlo/ReducedSelection_5* TTbar_amcatnlo_3/
mv TTbar_amcatnlo/ReducedSelection_6* TTbar_amcatnlo_3/
mv TTbar_amcatnlo/ReducedSelection_7* TTbar_amcatnlo_4/
mv TTbar_amcatnlo/ReducedSelection_8* TTbar_amcatnlo_4/
mv TTbar_amcatnlo/ReducedSelection_* TTbar_amcatnlo_5/
mkdir WZ_excl_1
mkdir WZ_excl_2
mkdir WZ_excl_3
mv WZ_excl/ReducedSelection_1* WZ_excl_1/
mv WZ_excl/ReducedSelection_2* WZ_excl_1/
mv WZ_excl/ReducedSelection_3* WZ_excl_2/
mv WZ_excl/ReducedSelection_4* WZ_excl_2/
mv WZ_excl/ReducedSelection_* WZ_excl_3/
mkdir ZZ_excl_1
mkdir ZZ_excl_2
mkdir ZZ_excl_3
mv ZZ_excl/ReducedSelection_1* ZZ_excl_1/
mv ZZ_excl/ReducedSelection_2* ZZ_excl_1/
mv ZZ_excl/ReducedSelection_3* ZZ_excl_2/
mv ZZ_excl/ReducedSelection_4* ZZ_excl_2/
mv ZZ_excl/ReducedSelection_* ZZ_excl_3/
mkdir WJets_madgraph_1
mkdir WJets_madgraph_2
mkdir WJets_madgraph_3
mv WJets_madgraph/ReducedSelection_11* WJets_madgraph_1/
mv WJets_madgraph/ReducedSelection_12* WJets_madgraph_1/
mv WJets_madgraph/ReducedSelection_13* WJets_madgraph_1/
mv WJets_madgraph/ReducedSelection_14* WJets_madgraph_1/
mv WJets_madgraph/ReducedSelection_15* WJets_madgraph_1/
mv WJets_madgraph/ReducedSelection_16* WJets_madgraph_1/
mv WJets_madgraph/ReducedSelection_1* WJets_madgraph_2/
mv WJets_madgraph/ReducedSelection_2* WJets_madgraph_2/
mv WJets_madgraph/ReducedSelection_3* WJets_madgraph_2/
mv WJets_madgraph/ReducedSelection_4* WJets_madgraph_2/
mv WJets_madgraph/ReducedSelection_* WJets_madgraph_3/

