#include "../interface/initInputTree.h"

// Declaration of leaf types
unsigned int RunNum;
unsigned int EvtNum;
float MET;
unsigned int NJets;
unsigned int BTags;
unsigned int NVtx;
float selectedIDIsoElectronsPt[100];
float selectedIDIsoElectronsEta[100];
float selectedIDIsoElectronsPhi[100];
float selectedIDIsoElectronsE[100];
unsigned int selectedIDIsoElectronsNum;
float selectedIDIsoMuonsPt[100];
float selectedIDIsoMuonsEta[100];
float selectedIDIsoMuonsPhi[100];
float selectedIDIsoMuonsE[100];
unsigned int selectedIDIsoMuonsNum;
float GenBosonPt[100];
float GenBosonEta[100];
float GenBosonPhi[100];
float GenBosonE[100];
int GenBoson_GenBosonPDGId[100];
float GenMuPt[100];
float GenMuEta[100];
float GenMuPhi[100];
float GenMuE[100];
float GenElecPt[100];
float GenElecEta[100];
float GenElecPhi[100];
float GenElecE[100];
unsigned int MHTJetsNum;
float MHTJetsPt[100];
float MHTJetsEta[100];
float MHTJetsPhi[100];
float MHTJetsE[100];
float MHTJets_bDiscriminator[100];

// List of branches
TBranch *b_RunNum; 
TBranch *b_EvtNum; 
TBranch *b_MET; 
TBranch *b_NJets;
TBranch *b_BTags;
TBranch *b_NVtx;
TBranch *b_selectedIDIsoElectronsPt;
TBranch *b_selectedIDIsoElectronsEta;
TBranch *b_selectedIDIsoElectronsPhi;
TBranch *b_selectedIDIsoElectronsE;
TBranch *b_selectedIDIsoElectronsNum;
TBranch *b_selectedIDIsoMuonsPt;
TBranch *b_selectedIDIsoMuonsEta;
TBranch *b_selectedIDIsoMuonsPhi;
TBranch *b_selectedIDIsoMuonsE;
TBranch *b_selectedIDIsoMuonsNum;
TBranch *b_GenBosonPt;
TBranch *b_GenBosonEta;
TBranch *b_GenBosonPhi;
TBranch *b_GenBosonE;
TBranch *b_GenBoson_GenBosonPDGId;
TBranch *b_GenMuPt;
TBranch *b_GenMuEta;
TBranch *b_GenMuPhi;
TBranch *b_GenMuE;
TBranch *b_GenElecPt;
TBranch *b_GenElecEta;
TBranch *b_GenElecPhi;
TBranch *b_GenElecE;
TBranch *b_MHTJetsNum;
TBranch *b_MHTJetsPt;
TBranch *b_MHTJetsEta;
TBranch *b_MHTJetsPhi;
TBranch *b_MHTJetsE;
TBranch *b_MHTJets_bDiscriminator;

void InitTree(TChain* nt)
{
  nt->SetBranchAddress("RunNum", &RunNum, &b_RunNum);
  nt->SetBranchAddress("EvtNum", &EvtNum, &b_EvtNum);
  nt->SetBranchAddress("MET", &MET, &b_MET);
  nt->SetBranchAddress("NJets", &NJets, &b_NJets);
  nt->SetBranchAddress("BTags", &BTags, &b_BTags);
  nt->SetBranchAddress("NVtx", &NVtx, &b_NVtx);
  nt->SetBranchAddress("selectedIDIsoElectronsPt", selectedIDIsoElectronsPt, &b_selectedIDIsoElectronsPt);
  nt->SetBranchAddress("selectedIDIsoElectronsEta", selectedIDIsoElectronsEta, &b_selectedIDIsoElectronsEta);
  nt->SetBranchAddress("selectedIDIsoElectronsPhi", selectedIDIsoElectronsPhi, &b_selectedIDIsoElectronsPhi);
  nt->SetBranchAddress("selectedIDIsoElectronsE",  selectedIDIsoElectronsE, &b_selectedIDIsoElectronsE);
  nt->SetBranchAddress("selectedIDIsoElectronsNum", &selectedIDIsoElectronsNum, &b_selectedIDIsoElectronsNum);
  nt->SetBranchAddress("selectedIDIsoMuonsPt", selectedIDIsoMuonsPt, &b_selectedIDIsoMuonsPt);
  nt->SetBranchAddress("selectedIDIsoMuonsEta", selectedIDIsoMuonsEta, &b_selectedIDIsoMuonsEta);
  nt->SetBranchAddress("selectedIDIsoMuonsPhi", selectedIDIsoMuonsPhi, &b_selectedIDIsoMuonsPhi);
  nt->SetBranchAddress("selectedIDIsoMuonsE",  selectedIDIsoMuonsE, &b_selectedIDIsoMuonsE);
  nt->SetBranchAddress("selectedIDIsoMuonsNum", &selectedIDIsoMuonsNum, &b_selectedIDIsoMuonsNum);
  nt->SetBranchAddress("GenBosonPt",  GenBosonPt, &b_GenBosonPt);
  nt->SetBranchAddress("GenBosonEta", GenBosonEta, &b_GenBosonEta);
  nt->SetBranchAddress("GenBosonPhi", GenBosonPhi, &b_GenBosonPhi);
  nt->SetBranchAddress("GenBosonE",   GenBosonE, &b_GenBosonE);
  nt->SetBranchAddress("GenBoson_GenBosonPDGId", GenBoson_GenBosonPDGId, &b_GenBoson_GenBosonPDGId);
  nt->SetBranchAddress("GenMuPt",  GenMuPt, &b_GenMuPt);
  nt->SetBranchAddress("GenMuEta", GenMuEta, &b_GenMuEta);
  nt->SetBranchAddress("GenMuPhi", GenMuPhi, &b_GenMuPhi);
  nt->SetBranchAddress("GenMuE",   GenMuE, &b_GenMuE);
  nt->SetBranchAddress("GenElecPt",  GenElecPt, &b_GenElecPt);
  nt->SetBranchAddress("GenElecEta", GenElecEta, &b_GenElecEta);
  nt->SetBranchAddress("GenElecPhi", GenElecPhi, &b_GenElecPhi);
  nt->SetBranchAddress("GenElecE",   GenElecE, &b_GenElecE);
  nt->SetBranchAddress("MHTJetsPt",  MHTJetsPt, &b_MHTJetsPt);
  nt->SetBranchAddress("MHTJetsEta", MHTJetsEta, &b_MHTJetsEta);
  nt->SetBranchAddress("MHTJetsPhi", MHTJetsPhi, &b_MHTJetsPhi);
  nt->SetBranchAddress("MHTJetsE",   MHTJetsE, &b_MHTJetsE);
  nt->SetBranchAddress("MHTJetsNum",   &MHTJetsNum, &b_MHTJetsNum);
  nt->SetBranchAddress("MHTJets_bDiscriminator",  MHTJets_bDiscriminator, &b_MHTJets_bDiscriminator);
}
